### ISSUE TITLE
DAV adds /?timeout=0 to quality SPARQL endpoint URL

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#278]
DAV adds /?timeout=0 to quality SPARQL endpoint URL, i.e. setting:
```yaml
- type: sparql
      # SPARQL endpoint.
      url: http://localhost:7200/repositories/nkod
```
makes DAV query using:
```
http://localhost:7200/repositories/nkod/?timeout=0&query=%0Aprefi....
```
1. i.e. `/` is added (this should not be necessary)
2. `timeout=0` parameter is added. This makes the query Virtuoso-specific, as GraphDB actually accepts only 1 param, and it needs to be `query`. So, if `timeout=0` is necessary here, we could put it at the end.
